/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BetterScroll: typeof import('./src/components/BetterScroll.vue')['default']
    Button: typeof import('./src/components/button/Button.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Main: typeof import('./src/components/drawer/main.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    MyComp: typeof import('./src/components/my-comp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanImage: typeof import('vant/es')['Image']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanProgress: typeof import('vant/es')['Progress']
    VanSlider: typeof import('vant/es')['Slider']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
